ExplosiveBow:
  name: "Explosive Bow"
  material: "BOW"
  type: "Weapon"
  rarity: "LEGENDARY"
  lore:
    properties:
      damage: 50
    ability:
      name: Explosive Shot
      details:
        - Shoot a explosive arrow that causes lots of damage
        - Arrow won't destroy blocks
  enchants:
    thunderbolt: 5
  attributes:
    damage: 50.0
FragGrenade:
  name: "Frag Grenade"
  material: "EGG"
  type: "Weapon"
  rarity: "LEGENDARY"
  lore:
    properties:
      damage: 50
    ability:
      name: TNT Party
      details:
        - Throw a *large* TNT explode with tons of damage
  enchants:
    thunderbolt: 5
  attributes:
    damage: 50.0
GrapplingHook:
  name: "Grappling Hook"
  material: "FISHING_ROD"
  type: "Util"
  rarity: "RARE"
  lore:
    ability:
      name: Hook
      details:
        - Using it will make you fly
  enchants:
    thunderbolt: 5
SnowGun:
  name: "Snow Gun"
  material: "DIAMOND_HOE"
  type: "Weapon"
  rarity: "ULTRA"
  lore:
    properties:
      damage: 25
      speed: 20
    ability:
      name: Let it go
      details:
        - Shoot Snowball that cause lots of damage
  enchants:
    thunderbolt: 5
  attributes:
    damage: 25.0
    moveSpeed: 0.2
TeleportDoor:
  name: "Teleport Door"
  material: "DIAMOND_SHOVEL"
  type: "Weapon"
  rarity: "GRAND"
  lore:
    properties:
      damage: 75
      speed: 20
    ability:
      name: Instant Teleport
      details:
        - Teleport to 12 blocks away from you
  enchants:
    thunderbolt: 5
  attributes:
    damage: 75.0
    moveSpeed: 0.2
Terminator:
  name: "Terminator"
  material: "BOW"
  type: "Weapon"
  rarity: "MYTHIC"
  lore:
    properties:
      damage: 50
      speed: 10
    ability:
      name: Triple Shot
      details:
        - Shoot three arrow at one time
        - Arrow deals 50% more damage
  enchants:
    sharpness: 20
    looting: 10
    thunderbolt: 5
  attributes:
    damage: 50.0
    moveSpeed: 0.1
WidowSword:
  name: "Widow Sword"
  material: "STICK"
  type: "Weapon"
  rarity: "MYTHIC"
  lore:
    properties:
      damage: 100
      speed: 20
    ability:
      name: Damage Multiplier
      details:
        - Damage dealt to mobs will be multiplied
        - Zombie + 100%
        - Skeleton + 100%
        - Spider + 100%
  enchants:
    sharpness: 20
    looting: 10
    thunderbolt: 5
  attributes:
    damage: 100.0
    moveSpeed: 0.2
  zombie: 100
  skeleton: 100
  spider: 100
InfiniteWaterBucket:
  name: "Infinite Water Bucket"
  material: "WATER_BUCKET"
  type: "Util"
  rarity: "EPIC"
InfiniteLavaBucket:
  name: "Infinite Lava Bucket"
  material: "LAVA_BUCKET"
  type: "Util"
  rarity: "EPIC"