name: NullValkyrie
version: '${project.version}'
main: me.night.nullvalkyrie.Main
api-version: 1.18
authors: [ NightKaly, Leocthl ]
description: Null Valkyrie
website: https://github.com/night0721/nullvalkyrie
depend: [ProtocolLib]
permissions:
  nv.command.use:
    default: true
