name: NullValkyrie
version: '${project.version}'
main: me.night.nullvalkyrie.NullValkyrie
api-version: 1.19
authors: [ NightKaly, Leocthl ]
description: Null Valkyrie
website: https://github.com/night0721/nullvalkyrie
permissions:
  nv.command.use:
    default: true
  nv.rank.add:
    default: op
